server:
  port: 8080

sources:
  - name : Images
    path : "C:\\Users\\ayede\\Desktop\\Akad Nikah"
  
  - name : Test Dir
    path : "C:\\Users\\ayede\\Desktop\\TestFile"

  - name : One Drive - Personal
    path : "C:\\Users\\ayede\\OneDrive"

  - name : Google Drive
    path : "X:\\"

  - name : Box Drive
    path : "Y:\\"